# Generated by Django 6.1 on 2026-09-16 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_review_unique_together_movierating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieRating',
            new_name='Rating',
        ),
    ]
