# Generated by Django 6.1 on 2026-09-16 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_movierating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='MovieRating',
        ),
    ]
